---
train:
  params:
    batch_size: 64
    epoch: 20
    lr: 0.00001
    decay: 0.1
    decay_step: 5000
    loss: L1Loss
  save:
    save_path: "/model/Full-Face-gaze360/trainOnMpii"
    model_name: weight
    step: 5
  data:
    image: "D:/gaze_estimate/dataset/FaceBased/MPIIFaceGaze/Image/train"
    label: "D:/gaze_estimate/dataset/FaceBased/MPIIFaceGaze/Label/train.label"
#    image: "D:\gaze_estimate\dataset\FaceBased\MPIIFaceGaze\Image"
#    label: "D:\gaze_estimate\dataset\FaceBased\MPIIFaceGaze\Label\p00.label"

  pretrains: "None"
test:
   load:
      begin_step: 5
      end_step: 20
      steps: 5
      load_path: "/model/Full-Face-gaze360/trainOnMpii"
      model_name: weight
   data:
      image: "D:/gaze_estimate/dataset/FaceBased/MPIIFaceGaze/Image/test"
      label: "D:/gaze_estimate/dataset/FaceBased/MPIIFaceGaze/Label/test.label"
reader: reader_mpii
