---
train:
  params:
    batch_size: 64
    epoch: 20
    lr: 0.00001
    decay: 0.1
    decay_step: 5000
    loss: L1Loss
  save:
    save_path: "/model/Full-Face-gaze360/trainOnMpii"
    model_name: weight
    step: 5
  data:
    image: "D:\\gaze_estimate\\dataset\\FaceBased\\MPIIFaceGaze\\Image"
    label: "D:\\gaze_estimate\\dataset\\FaceBased\\MPIIFaceGaze\\Label"
  pretrains: "None"
test:
   load:
      begin_step: 20
      end_step: 20
      steps: 5
      load_path: "/model/Full-Face-gaze360/trainOnMpii"
      model_name: weight
   data:
      image: "/home/cyh/GazeDataset20200519/FaceBased/MPIIFaceGaze/Image"
      label: "/home/cyh/GazeDataset20200519/FaceBased/MPIIFaceGaze/Label"
reader: reader_mpii
