---
train:
  params:
    batch_size: 64
    epoch: 20
    lr: 0.00001
    decay: 0.1
    decay_step: 5000
    loss: L1Loss
  save:
    save_path: "/model/Full-Face-gaze360"
    model_name: weight
    step: 5
  data:
    image: "~/autodl-tmp/gaze_estimate/dataset/FaceBased/Gaze360/Image"
    label: "~/autodl-tmp/gaze_estimate/dataset/FaceBased/Gaze360/Label/train.label"
  pretrains: "None"
test:
   load:
      begin_step: 5
      end_step: 20
      steps: 5
      load_path: "/model/Full-Face-gaze360"
      model_name: weight
   data:
      image: "~/autodl-tmp/gaze_estimate/dataset/FaceBased/Gaze360/Image"
      label: "~/autodl-tmp/gaze_estimate/dataset/FaceBased/Gaze360/Label/test.label"

reader: reader_gaze360
